# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  test:
    desc: Run tests
    cmds:
      - uv run pytest ./tests --cov=src --cov-report=html --cov-report=term -n auto
  benchmark:
    desc: Run benchmarks
    cmds:
      - uv run pytest ./benches --benchmark-only
